# Generated by Django 4.2 on 2025-08-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="avoid_high_impact",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscription",
            name="news_window_minutes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subscription",
            name="vol_threshold",
            field=models.FloatField(default=0.0),
        ),
    ]
