# Generated by Django 5.2.5 on 2025-08-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_subscription_avoid_high_impact_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="news_window_minutes",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="vol_threshold",
            field=models.FloatField(default=0.05),
        ),
    ]
